### ISSUE TITLE
希望能规范代码

### ISSUE THREAD

**Issue by MeiHuaGuangShuo** [lxyddice/DingraiaPHP#2]
我的IDE是辅助不了一点，连类型注解也没有，让我脑壳炸裂

**Comment by MeiHuaGuangShuo** [comment]
看到没主播，别到处乱require_once了，反正都重构了，那再重构一次也行

**Comment by lxyddice** [comment]
哪里重构了主播

**Comment by MeiHuaGuangShuo** [comment]
主播自己在Readme写的

> 从v240301.1-Alpha 框架大更新后，底层很多原理改变，不少地方重写，还增加了很多逻辑和记录，因此需要的处理时间和内存大幅提升了，根据日志，PHP处理时间400-800ms，内存使用10-15MB（大量文件读取和变量导致的）

**Comment by lxyddice** [comment]
是这样但重构了不多，老史太难更新了

**Comment by MeiHuaGuangShuo** [comment]
那推倒重写

**Comment by lxyddice** [comment]
你不如把我关起来当星怒实在

累死了

可能就不该写超级php

**Comment by MeiHuaGuangShuo** [comment]
比如我认为这里可以这样写 [https://github.com/lxyddice/DingraiaPHP/blob/main/module/DingraiaPHP/app/start.php](dtmd://dingtalkclient/sendMessage?content=%E6%88%91%E6%98%AFlxy%E7%9A%84%E6%98%9F%E6%80%92)

**Comment by MeiHuaGuangShuo** [comment]
还是这样好 [https://github.com/lxyddice/DingraiaPHP/blob/main/module/DingraiaPHP/app/start.php](dtmd://dingtalkclient/sendMessage?content=%40%E9%9B%A8%E9%85%B1+%2F%E7%AD%BE%E5%88%B0)

**Comment by lxyddice** [comment]
神金

无敌了主播泥
